# Config file for automatic testing at travis-ci.org

# after_success: travis_wait 30 codecov --token=d25a9eb9-4e77-4d38-8862-6d447be11830


language: python
python:
  - "3.7"      
install:
  - pip install --upgrade pip
  - pip install pytest-cov
  - pip install cython
  - pip install -U tox-travis codecov black
  - python setup.py install
  
  
jobs:
  include:
    # Deploy Documentation
    - stage: Docs
      python: "3.7"
      if: type != cron
      # Use previously defined before_install

      install:
        - pip install -r docs/requirements.txt

      script:
        - make clean -C docs/ html
        
    - stage: black
      python: "3.7"
      script: 
        - travis_wait 30 tox
        - travis_wait black --check KD_Lib
        - travis_wait black --check tests
      after_success: # Nothing to do

      deploy:
        - provider: pages
          edge: true
          token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
          keep_history: false
          local_dir: docs/build/html
          on:
            branch: master
        - provider: pages
          edge: true
          token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
          keep_history: false
          local_dir: docs/build/html
          on:
            tags: true

      deploy: 
        provider: pypi
        username: "__token__"
        password: $PYPI_API_TOKEN
        on: 
          tags: true
