from .common import BaseClass
from .vision import (
    BANN,
    CSKD,
    DML,
    Shake,
    RCO,
    TAKD,
    Attention,
    LabelSmoothReg,
    MeanTeacher,
    MessyCollab,
    NoisyTeacher,
    ProbShift,
    RKDLoss,
    SelfTraining,
    SoftRandom,
    VanillaKD,
    VirtualTeacher,
)
